version: "3.1"
services:
  springboot:
    image: srirampvs/springboot-app      
    ports:
    - 8080:8081
    environment:
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@123
    - MONGO_DB_HOSTNAME=mongo  
    networks:
    - springbootnetwork

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    networks:
    - springbootnetwork
    volumes:
    - mongodbebsvol:/data/db
networks:
  springbootnetwork:
volumes:
  mongodbebsvol:
